begin;

TRUNCATE TABLE sgdoc.tb_usuarios RESTART IDENTITY CASCADE;
TRUNCATE TABLE sgdoc.tb_unidades RESTART IDENTITY CASCADE;
TRUNCATE TABLE sgdoc.tb_usuarios_unidades RESTART IDENTITY CASCADE;
TRUNCATE TABLE sgdoc.tb_privilegios_usuarios RESTART IDENTITY CASCADE;

delete from sgdoc.tb_recursos_associacao where 
    id_recurso_pai in (select id from sgdoc.tb_recursos where nome ilike '%minuta%' or nome ilike '%SGDOCE%') 
        or
    id_recurso_filho in (select id from sgdoc.tb_recursos where nome ilike '%minuta%' or nome ilike '%SGDOCE%');

delete from sgdoc.tb_recursos where nome ilike '%minuta%' or nome ilike '%SGDOCE%';

insert into sgdoc.tb_usuarios (id,usuario,senha,nome,email,cpf,status,telefone) values (1,'admin',md5('admin'),'Administrador','admin@admin','99999999999',1,'6199999999');
insert into sgdoc.tb_usuarios (id,usuario,senha,nome,email,cpf,status,telefone) values (2,'arquivo',md5('arquivo'),'Arquivista','arquivo@arquivo','11111111111',1,'6199999999');
insert into sgdoc.tb_usuarios (id,usuario,senha,nome,email,cpf,status,telefone) values (3,'protocolo',md5('protocolo'),'Protocolizador','protocolo@protocolo','22222222222',1,'6199999999');
insert into sgdoc.tb_usuarios (id,usuario,senha,nome,email,cpf,status,telefone) values (4,'comum',md5('comum'),'Comum','comum@comum','33333333333',1,'6199999999');

insert into sgdoc.tb_unidades (id,nome,sigla,superior,tipo,up,codigo,uf,email,st_ativo,uop) values (1,'NOME DA INSTITUICAO (DEVE SER ALTERADO)','MATRIZ',null,5,0,null,1,'instituicao@instituicao',1,1); 
insert into sgdoc.tb_unidades (id,nome,sigla,superior,tipo,up,codigo,uf,email,st_ativo,uop) values (2,'Setor de Gerência da Informação','SGI',null,15,0,null,1,'sgi@sgi',1,1); 
insert into sgdoc.tb_unidades (id,nome,sigla,superior,tipo,up,codigo,uf,email,st_ativo,uop) values (3,'Arquivo','ARQUIVO',null,15,0,null,1,'arquivo@arquivo',1,1); 
insert into sgdoc.tb_unidades (id,nome,sigla,superior,tipo,up,codigo,uf,email,st_ativo,uop) values (4,'Protocolo','PROTOCOLO',null,15,0,null,1,'protocolo@protocolo',1,1); 
insert into sgdoc.tb_unidades (id,nome,sigla,superior,tipo,up,codigo,uf,email,st_ativo,uop) values (5,'Comum','COMUM',null,15,0,null,1,'comum@comum',1,1); 

insert into sgdoc.tb_usuarios_unidades (id_usuario,id_unidade,st_ativo) values (1,2,1);
insert into sgdoc.tb_usuarios_unidades (id_usuario,id_unidade,st_ativo) values (2,3,1);
insert into sgdoc.tb_usuarios_unidades (id_usuario,id_unidade,st_ativo) values (3,4,1);
insert into sgdoc.tb_usuarios_unidades (id_usuario,id_unidade,st_ativo) values (4,5,1);

insert into sgdoc.tb_privilegios_usuarios (id_usuario,id_recurso,permissao) 
    select 1,id,1 from sgdoc.tb_recursos;

--arquivo
insert into sgdoc.tb_privilegios_usuarios (id_usuario,id_recurso,permissao) 
    select 2,id,1 from sgdoc.tb_recursos where id in (703,702,701,700,699,698,697,696,695,694,693,692,691,690,689,
688,687,686,685,684,683,682,681,680,679,678,677,676,675,674,673,672,671,
670,669,668,667,666,665,664,663,662,661,660,659,658,657,656,655,654,653,652,651,650,649,
648,647,646,645,644,643,642,641,640,639,638,637,636,635,634,633,632,631,630,629,628,627,626,625,624,623,
622,621,620,619,618,617,616,615,614,613,612,611,610,609);

--protocolo
insert into sgdoc.tb_privilegios_usuarios (id_usuario,id_recurso,permissao) 
    select 3,id,1 from sgdoc.tb_recursos where id in (806,805,804,803,802,801,800,799,798,797,796,795,794,793,792,791,790,789,
788,787,786,785,784,783,782,781,780,779,778,777,776,775,774,773,772,771,770,769,768,767,766,765,764,763,762,761,760,759,758,
757,756,755,754,753,752,751,750,749,748,747,746,745,744,743,742,741,740,739,738,737,736,735,734,733,732,731,730,729,
728,727,726,725,724,723,722,721,720,719,718,717,716,715,714,713,712,711,710,709,708,707,706,705,704);

--comum
insert into sgdoc.tb_privilegios_usuarios (id_usuario,id_recurso,permissao) 
    select 4,id,1 from sgdoc.tb_recursos where id in (894,893,892,891,890,889,888,887,886,885,884,883,882,881,880,
879,878,877,876,875,874,873,872,871,870,869,868,867,866,865,864,863,862,861,860,859,858,857,856,855,854,853,852,
851,850,849,848,847,846,845,844,843,842,841,840,839,838,837,836,835,834,833,832,831,830,829,828,827,826,825,824,
823,822,821,820,819,818,817,816,815,814,813,812,811,810,809,808,807);

--assuntos
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ABASTECIMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ABERTURA DE DOSSIE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ABERTURA DE PROCESSO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ABONO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ABONO DE CARGO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ABONO DE FALTA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ABONO DE PERMANENCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ABONO PECUNIARIO ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO CAUTELAR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO CIVIL PUBLICA ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO CONJUNTA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO DE COBRANCA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO DE DESAPROPRIACAO.',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO DE PREVENCAO A INCENDIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO DE USUCAPIAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO DISCIPLINAR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO FISCALIZADORA EM MOSAICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO JUDICIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO ORDINARIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO PENAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO POPULAR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACAO TRABALHISTA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACERTO DE CONTAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('Acervo',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACORDO ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACORDO DE COOPERACAO TECNICA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACORDO DE GESTAO EM UC',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACORDO JUDICIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ACUMULO DE CARGO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ADICIONAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ADICIONAL DE INSALUBRIDADE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ADICIONAL DE PERICULOSIDADE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ADICIONAL NOTURNO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ADVERTENCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AERONAVES',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AFASTAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AFASTAMENTO DA FUNCAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AFASTAMENTO DE FUNCAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AFASTAMENTO DO PAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AFASTAMENTO PARA MANDADO ELETIVO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AFASTAMENTO PARA MANDATO ELETIVO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AGRADECIMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AJUDA DE CUSTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AJUSTE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ALERTA DE DESMANTAMENTO NA AMAZONIA LEGAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ALISTAMENTO ELEITORAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ALOJAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ALTERACAO DE DADOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ALTERACAO DE FERIAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ALVARA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AMAZONIA LEGAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('Analise de Contestacao',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ANALISE JURIDICA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ANDAMENTO DE PROCESSO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ANISTIADOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ANUENCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('APOIO AO COMBATE A INCENDIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('APOIO NAUTICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('APOIO POLICIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('APOSENTADORIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('APREENSAO DE ANIMAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('APREENSAO DE BENS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('APREENSAO DE MADEIRA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('APREENSAO DE PRODUTOS QUIMICOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('APRESENTACAO DE SERVIDOR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('APROVEITAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AQUICULTURA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AQUISICAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AQUISICAO DE EQUIPAMENTOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ARQUIVAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ARQUIVAMENTO DE DOCUMENTOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ARQUIVAMENTO DE PROCESSO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ARRECADACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ASSEMBLEIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ASSENTAMENTO FUNCIONAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ASSISTENCIA MEDICA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ATA DE REGISTRO DE PRECO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ATESTADO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ATESTADO DE CAPACIDADE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ATESTADO DE CAPACIDADE FISICA E MENTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ATESTADO MEDICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ATIVIDADES DE VISITACAO E ECOTURISMO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUDIENCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUDIENCIA PUBLICA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUDITORIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUTO DE INFRACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUTORIZACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUTORIZACAO PARA LICENCIAMENTO AMBIENTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUXILIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUXILIO ALIMENTACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUXILIO FUNERAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUXILIO MORADIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUXILIO NATALIDADE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUXILIO PRE ESCOLA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AUXILIO TRANSPORTE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AVALIACAO DE DESEMPENHO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AVERBACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AVERBACAO DE RESERVA LEGAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('AVISO DE COBRANCA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BAIXA DE DEBITOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BALANCETE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BALANCO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BANCO DE DADOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BANCO DE DADOS - MONITORAMENTO AMBIENTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BENEFICIARIOS DE UNIDADES DE CONSERVACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BENS DE CONSUMO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BENS IMOVEIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BENS PATRIMONIAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BLOQUEIO DE CREDITO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BLOQUEIO DE PAGAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BLOQUEIO DE SERVICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BLOQUEIO JUDICIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BNDES',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BOLETIM DE FREQUENCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BOLETIM DE OCORRENCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BOLETIM DE SERVICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BOLETIM INFORMATIVO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('BOLETIM TECNICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CADASTRO SIAFI',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CAPACITACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CARGO EM COMISSAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CARTAO CORPORATIVO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CARTAO DE MANUTENCAO E ABASTECIMENTO DE VEICULOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CERTIFICADO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CERTIFICADO GTAD45',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CESSAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CESSAO DE SERVIDOR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COLABORADOR EVENTUAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMBATE E PREVENCAO A INCENDIOS FLORESTAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMISSAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMISSAO DE SINDICANCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMITE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMPENSACAO AMBIENTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMPENSACAO DE GREVE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMPENSACAO DE HORAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMPENSACAO DE RESERVA LEGAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMPROVANTE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMPROVANTE DE PAGAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMPROVANTES',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('COMUNICACAO DE INFRACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONCURSO PUBLICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONFIDENCIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONFORMIDADE DOCUMENTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONGRESSO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONSELHO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONSELHO CONSULTIVO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONSELHO DELIBERATIVO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONSOLIDACAO DE LIMITES',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONSULTA PUBLICA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONSULTORIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONTRADITA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONTRATO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONTRATO DE CONCESSAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONVENIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONVITE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CONVOCACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CORREDOR ECOLOGICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CORRESPONDENCIA CONFIDENCIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CORRESPONDENCIA FECHADA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CORRESPONDENCIA PARTICULAR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CREDITO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CREDITO EXTRAORDINARIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CREDITO ORCAMENTARIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CREDITOS ADICIONAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CREDITO SUPLEMENTAR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CRIACAO DE CENTRO DE PESQUISA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CRIACAO DE UNIDADE DE CONSERVACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CURRICULO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CURSO DE BRIGADISTA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CURSO DE CAPACITACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('CURSO DE ESPECIALIZACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DANFE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DECISAO ADMINISTRATIVA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DECISAO JUDICIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DECLARACAO CONJUNTA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DECRETO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DEFESA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values (' DEMARCACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DEMISSAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DEMONSTRATIVO DE DESPESA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DENUNCIA ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DEPENDENTES DE SERVIDOR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESAPROPRIACAO ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESARQUIVAMENTO DE DOCUMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESARQUIVAMENTO PROCESSO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESBLOQUEIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESCENTRALIZACAO DE CREDITO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESCENTRALIZACAO DE RECURSOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESCONTO EM FOLHA DE PAGAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESOCUPACAO DE AREA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESONERACAO DE RESERVA LEGAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESPACHO SANEADOR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESPESA COM PESSOAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESPESAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DESTAQUE ORCAMENTARIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DEVOLUCAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DEVOLUCAO DE BEM PATRIMONIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DEVOLUCAO DE DOCUMENTOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DIARIA E PASSAGEM - SCDP',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DILATACAO DE PRAZO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DISSERTACAO DE MESTRADO ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DIVULGACAO ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DOACAO DE BENS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DOACAO DE MADEIRA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('DOACAO DE MATERIAL APREENDIDO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ECOTURISMO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EDITAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ELOGIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EMBARCACOES',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EMERGENCIA AMBIENTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EMPRESTIMO DE ANIMAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ENCONTRO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ENQUADRAMENTO DE SERVIDOR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ENTREVISTA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EQUIPAMENTO DE COMBATE A INCENDIO FLORESTAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EQUIPAMENTOS HARDWARE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ESPECIES AMEACADAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ESTABILIDADE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ESTAGIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ESTAGIO PROBATORIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ESTATUTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ESTRUTURA ORGANIZACIONAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ESTUDO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ESTUDO DE IMPACTO AMBIENTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EXONERACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EXPEDICAO DE MAPEAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EXPLORACAO FLORESTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EXPORTACAO DE ANIMAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EXPORTACAO DE PLANTAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('EXTRAVIO DE DOCUMENTOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FABRICA DE SOFTWARE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FALECIMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FATURA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FATURA DE SERVICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FATURA DE SERVICO BASICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FERIAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FISCALIZACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FOLHA DE PONTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FORMULARIO SDP',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FORMULARIO SIAFI',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FORUM',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FUNCAO GRATIFICADA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('FUNDO DE GARANTIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('GARAGEM',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('GEOREFERENCIAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('GESTAO DE UNIDADE DE CONSERVACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('GRATIFICACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('GRATIFICACAO DE QUALIFICACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('GRATIFICACAO POR ENCARGO DE CURSO OU CONCURSO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('GRC - GUIA DE REMESSA DE CORRESPONDENCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('GRM - GUIA DE REMESSA DE MALOTE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('GRU - GUIA DE RECOLHIMENTO DA UNIAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('GRUPO DE TRABALHO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('HELP DESK',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('HORARIO ESPECIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('IDENTIFICACAO FUNCIONAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('IMPORTACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('IMPORTACAO DE ANIMAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('IMPORTACAO DE PLANTAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('IMPOSTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('IMPOSTO DE RENDA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INCLUSAO DE DOCUMENTOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INDENIZACAO DE POSSES',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INDICACACAO DE NOMEACAO GTAD60',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INDICACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INDICACAO DE FUNCIONARIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INDICACAO DE FUNCIONARIO GTAD70',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INFORMACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INFORMACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INFRACAO DE TRANSITO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INQUERITO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INQUERITO  CIVIL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INTERNET',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INTERVENCAO DE UNIDADE DE CONSERVACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INTIMACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INVASAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('INVENTARIO FLORESTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('JORNADA DE TRABALHO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('JUNTA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('KIT DE DIVULGACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LAUDO PERICIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LAUDO PERICIAL DE INCENDIO FLORESTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LEVANTAMENTO TOPOGRAFICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICENCA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICENCA DE PESQUISA EM UNIDADES DE CONSERVACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICENCA MATERNIDADE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICENCAMENTO AMBIENTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICENCA PARA CAPACITACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICENÇA PARA PESQUISA MINERAL EM AREA DE AMORTECIMENTO DA RESEX RIO CAJARI/AP',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICENCA PARA SERVICO MILITAR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICENCA POR INTERESSES PARTICULARES',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICENCA POR MOTIVO DE DOENCA ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICENCA PREMIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICENCIAMENTO AMBIENTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LICITACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LOTACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('LOTACAO DE PESQUISADOR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MANDADO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MANEJO DE ANIMAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MANEJO DE ESPECIES AMEACADAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MANEJO DE ESPECIES EXOTICAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MANEJO DE ESPECIES INVASORAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MANEJO FLORESTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MANIFESTACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MANUTENCAO DE UNIDADES DE CONSERVACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MATERIAL CONTROLADO DE FISCALIZACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MATERIAL PARA CURSO DE CAPACITACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MATERIAL PARA CURSO DE FISCALIZACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MEDIDA ADMINISTRATIVA CAUTELAR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MINUTA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MOCAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MONITORAMENTO DA BIODIVERSIDADE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MONITORAMENTO DO PLANO DE MANEJO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MOSAICO DE AREAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('MULTA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('NADA CONSTA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('NOMEACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('NOTA DE EMPENHO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('NOTA FISCAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('NOTA TECNICA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('NOTIFICACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values (' NOTIFICACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('OBRA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('OBRA - MATERIAL DE CONSTRUCAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('OCORRENCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('OFICINA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('OFICINA DE CAPACITACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('OFICIO CIRCULAR.',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('OPERACAO DE FISCALIZACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ORDEM DE FISCALIZACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ORDEM DE PAGAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ORDEM DE SERVICO CONTRATUAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ORGANOGRAMA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PALESTRA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PARCERIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PARECER',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PARECER TECNICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PASSAPORTE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PEDIDO DE RESCISAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PENSAO ALIMENTICIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PENSAO JUDICIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PENSAO POR FALECIMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values (' PERICIA MEDICA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PERICIA MEDICA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PERMUTA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PESQUISA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PESQUISA CIENTIFICA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PESQUISA FUNDIARIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PESQUISA MINERAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PLACA PARA SINALIZACAO DE VISITANTE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PLANEJAMENTO ESTRATEGICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PLANO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PLANO DE ACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PLANO DE MANEJO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PLANO DE PROTECAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PLANO DE SAUDE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PLAQUETA PATRIMONIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('POLITICAS DE EDUCACAO AMBIENTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('POPULACOES EXTRATIVISTAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('POPULACOES TRADICIONAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PORTARIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PORTE DE ARMAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('POSSE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PREGAO ELETRONICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PRESTACAO DE CONTAS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PRESTACAO DE CONTAS DE SUPRIMENTO DE FUNDOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PRESTACAO DE SERVICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PRESTACAO DE SERVICO AUTONOMO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PRESTACAO DE SERVICOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values (' PROCEDIMENTO ADMINISTRATIVO ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROCEDIMENTO ADMINISTRATIVO N° 08104.000377/96-09',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values (' PROCEDIMENTO MINISTERIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROCESSO ADMINISTRATIVO DISCIPLINAR ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROCESSO ADMNISTRATIVO DISCIPLINAR. INTIMACAO TESTEMUNHAS. AUDIENCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PRODUTO DE CONSULTORIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PRODUTO FLORESTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROGRAMA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROGRAMA BOLSA VERDE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROGRAMA DE VOLUNTARIADO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROGRAMA PIBIC',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROGRAMAS AMBIENTAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROGRESSAO FUNCIONAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROJETO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROJETO DE LEI DE SERVICOS AMBIENTAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROJETO DE PESQUISA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROJETO DE TRABALHO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROJETO PEIXE BOI',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROJETOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROJETO TAMAR',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROMOCAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROPOSTA DE CRIACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROPOSTA DE CRIACAO DE UNIDADES DE CONSERVACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PROPOSTA ORCAMENTARIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PRORROGACAO DE CONTRATO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PUBLICACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('PUBLICACAO EM DIARIO OFICIAL DA UNIAO ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('READAPTACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REAJUSTE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECADASTRAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECATEGORIZACAO DE UNIDADE DE CONSERVACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECIBOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECLAMACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECOLHIMENTO DE DIVIDA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECONDUCAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECONHECIMENTO DE DIVIDA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECRUTAMENTO E SELECAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECUPERACAO DE AREA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECURSO ADMINISTRATIVO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECURSO ORCAMENTARIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RECURSO PNUD',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REDISTRIBUICAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REFLORESTAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REFORMA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REGIMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REGISTRO NO ISSN OU ISBN',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REGULAMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REGULARIZACAO FUNDIARIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REINTEGRACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RELATORIO CONSOLIDADO DE FISCALIZACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RELATORIO CONSOLIDADO DE OPERACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RELATORIO DE ATIVIDADE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values (' RELATORIO DE IMPACTO AMBIENTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RELATORIO DE PESQUISA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RELATORIO DE VIAGEM',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RELATORIO DE VISTORIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RELATORIO FINANCEIRO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REMOCAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RENOVACAO DE CONTRATO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REPACTUACAO DE CONTRATO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REPOSICAO DE GREVE GTAD63',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REPOSICAO FLORESTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REQUERIMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RESCISAO DE CONTRATO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RESERVA FLORESTAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RESERVA LEGAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RESOLUCAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RESPOSTA A DOCUMENTO OFICIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RESSARCIMENTO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('RETENCAO DE IMPOSTO SOBRE SERVICO - ISS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REUNIAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('REVERSAO ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SEGURO OBRIGATORIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SEMINARIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SEPAG',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SERVICO DE CORREIOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SERVICO DE EDITORACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SERVICO DE INFRAESTRUTURA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SERVICO DE REDE ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SERVICO DE REPROGRAFIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SERVICOS AMBIENTAIS ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SERVICOS BASICOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SINALIZACAO DO PERIMETRO DAS UNIDADES DE CONSERVACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SINDICANCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SINISTRO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SISBIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SISTEMA INTEGRADO DE ADMINISTRACAO DE SERVICO GERAIS - SIASG',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SISTEMAS SOFTWARE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SITIOS SITE ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SOBREPOSICAO DE UNIDADES DE CONSERVACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SOLENIDADES, COMEMORACOES E HOMENAGENS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SUBSIDIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SUBSTITUICAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SUBSTITUICAO DE FUNCIONARIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SUBSTITUICAO DE PESSOAL ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SUPRIMENTO DE FUNDOS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('SUSPENSAO ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TAXA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TEMPO DE CONTRIBUICAO ',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TEMPO DE SERVICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TERMO ADITIVO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TERMO DE APREENSAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TERMO DE COMPROMISSO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TERMO DE COOPERACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TERMO DE ENTREGA DE BEM APREENDIDO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TERMO DE POSSE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TERMO DE RECIPROCIDADE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TERMO DE REFERENCIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TERMO DE RESPONSABILIDADE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TERMO DE RESPOSABILIDADE',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TOMBAMENTO DE VEICULO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TRANSFERENCIA DE AREA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TRANSPORTE DE FUNCIONARIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TRANSPORTE DE MATERIAL',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('TRANSPORTE MOBILIARIO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('UNIFORMES',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('VEICULO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('VEICULOS OFICIAIS',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('VERIFICACAO DE LIMITES DA UC',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('VIAGEM A SERVICO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('VISITACAO',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('VISITA TECNICA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('VISTORIA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('VISTORIA TECNICA',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('WORKSHOP',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('WORSHOP',1,1);
insert into sgdoc.tb_documentos_assunto (assunto,usuario,homologado) values ('ZONA DE AMORTECIMENTO',1,1);
 
commit;
